services:
  db:
    image: mysql:9.3.0
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    networks:
      - backend_network


  web:
    build:
      context: ./src
    environment:
      DB_NAME: ${db_name}
      DB_PASSWORD: password
    ports:
      - 5000:5000
    networks:
      - backend_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  backend_network:

