name: Docker build and test

on:
   push: 
      branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: start with docker compose
        run: docker compose up -d

      - name: Wait for the app to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "App is up!"
              break
            else
              echo "Waiting for app..."
              sleep 3
            fi
          done

      - name: test curl (unit test)
        run: curl http://localhost:5000/

      - name: Show logs (for debugging)
        if: failure()
        run: docker compose logs

      - name: stop compose
        run: docker compose down
