name: Docker build and test

on:
   push: 
      branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: start with docker compose
        run: docker compose up -d

      - name: Wait for the app to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "App is up!"
              break
            else
              echo "Waiting for app..."
              sleep 3
            fi
          done

      - name: test curl (unit test)
        run: curl http://localhost:5000/

      - name: Show logs (for debugging)
        if: failure()
        run: docker compose logs

      - name: stop compose
        run: docker compose down

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: tag and push image to ecr
        run: |
          echo "Building image with tag"
          docker build -t ${{ vars.AWS_ECR_ENTRY_TRACKER }}:latest ./src
          docker push ${{ vars.AWS_ECR_ENTRY_TRACKER }}:latest
          docker build -t ${{ vars.AWS_ECR_ENTRY_TRACKER }}:1.0.1 ./src
          docker push ${{ vars.AWS_ECR_ENTRY_TRACKER }}:1.0.1
