name: Docker build and test

on:
   push: 
      branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: start with docker compose
        run: docker compose up -d

      - name: test curl (unit test)
        run: curl http://localhost:5000/

      - name: stop compose
        run: docker compose down
